"""add is_admin, feature_flags, lesson cms fields

Revision ID: 77b10cc16541
Revises: 0004
Create Date: 2026-06-15 23:37:32.728204
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '77b10cc16541'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('behavior_on_inactive', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=False)
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_index(op.f('ix_lesson_images_id'), 'lesson_images', ['id'], unique=False)
    op.add_column('lessons', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('lessons', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('image_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('lessons', sa.Column('alt_text', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('placeholder_text', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_token_blocklist_user_id'), table_name='token_blocklist')
    op.create_index(op.f('ix_token_blocklist_id'), 'token_blocklist', ['id'], unique=False)
    op.alter_column('user_progress', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.alter_column('user_progress', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_token_blocklist_id'), table_name='token_blocklist')
    op.create_index(op.f('ix_token_blocklist_user_id'), 'token_blocklist', ['user_id'], unique=False)
    op.drop_column('lessons', 'placeholder_text')
    op.drop_column('lessons', 'alt_text')
    op.drop_column('lessons', 'image_active')
    op.drop_column('lessons', 'image_url')
    op.drop_column('lessons', 'active')
    op.drop_index(op.f('ix_lesson_images_id'), table_name='lesson_images')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_id'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
